#cloud-config
# Add the group 'deploy-users' to the system. This group will gain
#  sudo access in the 'write_files' step
groups:
  - deploy-users

# Add Ansible user to manage the system
users:
  - default
  - name: mrrobot
    primary_group: mrrobot
    groups:
      - users
      - sudo
      - deploy-users
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCn28Mr9fCijSTE18mLFh0DsFPtaWWs3i23kGIlWM+vmbx6jwAuZn9HyfPwPqCaiBLswHAEgIos5spfPfziaWSJ4jgOVElrFuiBJdtRFfNT+05QMOke+utnEAeFB2vdjgrE5n8AR6AKnV0ubrgRwHgSfqndweQzDart0ZBp79/N0KQHpRScqUZucY0wR4pjNu2aQZefo58h4zu5hvEuq0NxjOPFaMJY2cZimYRXidpAaaVLR/yg2TZltMzUFuBR45sBoNH3EqXGWwNX0CejZRQouWdCQi2bNSJAksEEfCZPZ65i7IXeVTv+Izavhizw+Qlm9qGk39Zmhd3DHgf9OT65G2RUwigx8CiGmYznBg4WTCuc6i/yHTyhyVG3LDJ4qDgebgNFSI/9y3eMG+CEVH6ldhCIPARrVtl2RiXbuyIkjimfox2mF9KY5PRo86JEawrIv1fRYcSeLcjK4eoydNRXvq4ON6zcbluQuekxmyQdihgDciUfJr6kF+V4v0T9KVh4uCn0Mv96w/b0K9gs6sLnx/cxF/nRiaEYk3+kdOCXVEgFFAQBWlhNllSmTi0e6wrLfQnAciUsndzCZhFRtiRNghEyM2JAkqXr6ZPZtSlKUxf0eQluYDFLiwmiGLjCczI1O1HvbHylMegxHeRlOMJcomFXl/T3Wv6dNz60nuZFxw== niekkeijzer@Nieks-MacBook-Pro.local
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9tY7Eyi46Ti+WNUGuL9LDyWiNH0KWM0KErWxm6N1kl+mhFnYI/6m9VHvCzHqP6ldSL3NH54ULTpv3f7ObQXCjP6mwkpDTY9/dwL7iFRQ4EkFfDFCP/7+ACGxOrEah0jpwifsbB+OEMKIoxBioPpvO9H9YAmSvLdI5svq+QRPKzYEvpVuRi74+xEoGTSeat+w8St01jczGBV4eZm5PxGOZCKG4hiOJtvqW6JkhHlWXqK9DPO5r9UxeRFX6tbmShqzdUbgMPpgow4rl9ZRbuzovr+abO5YOyeXhpmCLX42RExf5FvmFTqvaSJKwPwihveBxaSZcjgoE3caFJSdlCXioLrSctkZZSIOJ0/6ovoSv1qOr1N3qOSVCR8XbPB4lFOe+r94e8sBkPlj9/TH+pYnZbNPISd8IIIOAyNwDZof2UwhSUdtOQ1lTXT9BL9YOJ1cPzDYp+JZ43yfiqZUQ70LrTcStfOHFsJsZYnBqquLKZUW82cwerUcDt6ZvfxHEZBYzMqb9268mda3Ul2xX1hfkLQLpiQiYYtFTYU2F0olXqAnUVR9LT6FLBumSdFhro5z8NDaEchQ6PuGFGpvALGtFWAYa7JXsbDUGfE5kPYMoFHdo8MPWkCMId6+J4tlQQmnEY9VOdjdM21+4jWwth9OME6kdxiqTKt5Tb07LJNEm6Q== niek@qabanahq

write_files:
  - path: /etc/sudoers.d/40-deploy-users
    content: '%deploy-users ALL=(ALL:ALL) NOPASSWD:ALL'
    owner: 'root:root'
    permissions: '0440'

