#cloud-config
# Add the group 'deploy-users' to the system. This group will gain
#  sudo access in the 'write_files' step
groups:
  - deploy-users

# Disable SSH password login
ssh_pwauth: false

# Add Ansible user to manage the system
users:
  - default
  - name: mrrobot
    primary_group: mrrobot
    groups:
      - users
      - sudo
      - deploy-users
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCn28Mr9fCijSTE18mLFh0DsFPtaWWs3i23kGIlWM+vmbx6jwAuZn9HyfPwPqCaiBLswHAEgIos5spfPfziaWSJ4jgOVElrFuiBJdtRFfNT+05QMOke+utnEAeFB2vdjgrE5n8AR6AKnV0ubrgRwHgSfqndweQzDart0ZBp79/N0KQHpRScqUZucY0wR4pjNu2aQZefo58h4zu5hvEuq0NxjOPFaMJY2cZimYRXidpAaaVLR/yg2TZltMzUFuBR45sBoNH3EqXGWwNX0CejZRQouWdCQi2bNSJAksEEfCZPZ65i7IXeVTv+Izavhizw+Qlm9qGk39Zmhd3DHgf9OT65G2RUwigx8CiGmYznBg4WTCuc6i/yHTyhyVG3LDJ4qDgebgNFSI/9y3eMG+CEVH6ldhCIPARrVtl2RiXbuyIkjimfox2mF9KY5PRo86JEawrIv1fRYcSeLcjK4eoydNRXvq4ON6zcbluQuekxmyQdihgDciUfJr6kF+V4v0T9KVh4uCn0Mv96w/b0K9gs6sLnx/cxF/nRiaEYk3+kdOCXVEgFFAQBWlhNllSmTi0e6wrLfQnAciUsndzCZhFRtiRNghEyM2JAkqXr6ZPZtSlKUxf0eQluYDFLiwmiGLjCczI1O1HvbHylMegxHeRlOMJcomFXl/T3Wv6dNz60nuZFxw== niekkeijzer@Nieks-MacBook-Pro.local
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCpdO5x0bj4YoGP/23NYhxHXqTW67K7JQR/WF+SirPzIKRQXg/eMGHORyOGpsWZnvD8V8k2JQZ7hInb7hqzSQBO/t9k+TU652BO7wKv88kZTsgdTORL9uOewGjTcIZNW3G7D3YzmXRFyMJaB+bgaMdr43a8lxeRksH9he5ZPb/jOuEL8yiIJ5MNmFZWPIjyuPVd3qsIzuy0F+SRhYXGKjnd1h7punNorBXLkKbl5Is/DnCH9KbliBunSbH9cnAg1y2rCWAzS3n/4QqV1pETAXy3dXoIBa9JeZoB67iFcDisbPL9blPODv1AmY0R0vCXMepKTFn4smsVETA33zPf/g87SoavY1V9dxgANb/pjlnQbxLVU8IUPTAyxCgEvxw/ZKUZ91You/sRjAArPt3VFUpOLvyg76O7HxXLncqSdl3yhNFZWluoLIuuCTXn7fyjhAKy08O+PV7i1UQgY1+ny+sXlsHUv6qYFS729d61GyXXUtcTGs5v85NxT8a4T2u4nSqvSJRK1jueOGpL8ItLEaupVyE3HvoXRo+gDwGeXS2ypWAK396Cn/YfAL6ftP69GB7PYu/L2lHobFCx4Ot0F219t68xCjKBW5Bea8at5LkCFGaqhX5aFq2YWpwDMAScQAdedfO3tHVJeSo6Q6a3g7ieAd/DehWWDXRqcGqLZEXfzw== niekkeijzer@iMac-van-Niek.local


write_files:
  - path: /etc/sudoers.d/40-deploy-users
    content: '%deploy-users ALL=(ALL:ALL) NOPASSWD:ALL'
    owner: 'root:root'
    permissions: '0440'

package_update: true 
package_upgrade: true 

packages: 
  - linux-virtual-hwe-20.04
  - fail2ban
  - ufw
  - apparmor
  - apparmor-profiles 

runcmd:
  - apt install -f -y 
  - printf "[sshd]\nenabled = true\nbanaction = ufw\n" > /etc/fail2ban/jail.local
  - ufw limit ssh/tcp
  - ufw allow in on eth0
  - ufw logging off
  - ufw enable 
  - sed -i -e "/^PermitRootLogin/s/^.*$/PermitRootLogin no/" /etc/ssh/sshd_config
  - sed -i -e "/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/" /etc/ssh/sshd_config
  - sed -i -e "/^X11Forwarding/s/^.*$/X11Forwarding no/" /etc/ssh/sshd_config
  - systemctl enable fail2ban
  - systemctl enable ufw 
  - apt purge -y lxd lxd-client snapd
  - apt clean 
  - apt auto-clean

power_state:
  mode: reboot 
  timeout: 5
  condition: true
