#cloud-config
# Add the group 'deploy-users' to the system. This group will gain
#  sudo access in the 'write_files' step
groups:
  - deploy-users

# Disable SSH password login
ssh_pwauth: false

# Add Ansible user to manage the system
users:
  - default
  - name: mrrobot
    primary_group: mrrobot
    groups:
      - users
      - sudo
      - deploy-users
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCn28Mr9fCijSTE18mLFh0DsFPtaWWs3i23kGIlWM+vmbx6jwAuZn9HyfPwPqCaiBLswHAEgIos5spfPfziaWSJ4jgOVElrFuiBJdtRFfNT+05QMOke+utnEAeFB2vdjgrE5n8AR6AKnV0ubrgRwHgSfqndweQzDart0ZBp79/N0KQHpRScqUZucY0wR4pjNu2aQZefo58h4zu5hvEuq0NxjOPFaMJY2cZimYRXidpAaaVLR/yg2TZltMzUFuBR45sBoNH3EqXGWwNX0CejZRQouWdCQi2bNSJAksEEfCZPZ65i7IXeVTv+Izavhizw+Qlm9qGk39Zmhd3DHgf9OT65G2RUwigx8CiGmYznBg4WTCuc6i/yHTyhyVG3LDJ4qDgebgNFSI/9y3eMG+CEVH6ldhCIPARrVtl2RiXbuyIkjimfox2mF9KY5PRo86JEawrIv1fRYcSeLcjK4eoydNRXvq4ON6zcbluQuekxmyQdihgDciUfJr6kF+V4v0T9KVh4uCn0Mv96w/b0K9gs6sLnx/cxF/nRiaEYk3+kdOCXVEgFFAQBWlhNllSmTi0e6wrLfQnAciUsndzCZhFRtiRNghEyM2JAkqXr6ZPZtSlKUxf0eQluYDFLiwmiGLjCczI1O1HvbHylMegxHeRlOMJcomFXl/T3Wv6dNz60nuZFxw== niekkeijzer@Nieks-MacBook-Pro.local
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDg5XdCbXLR4A/YPYmIbg1eO3fLqjP2b1+0GwrqhlUjOtb2/baF5A3AyIhxJ5tKjizrXs0VTcHmcpgV7jLyGixDdYx6qt1hqBCXFt+h+4zPdqaYn+jv78pc7BsB/q274T0Xi2xyFO1+8UhkRqwTwXq8QLQYTSeyFXTnBLu+qMScxbW5yplWwEV0HBiZMjUJX7waEzib0LXj5JdlQvlLNKconvO1CYmwg0T6U8TeaJQmOv5M8NmhLYfqrBPmbjCLjk9Jun9s5Ca+ZezPSy0uN9WjEJSdUbxEKdkgbK/Eu3Nq3r0E5apiQrAhvnKh4wJG6NbHf6w7Y5ecpD6u536UAqYpc6rp97ymUf1k/IbiqEQbKuXzUVtv5XcN53UtZ3gTGqXxsRrvhOQaHnDKWl/yvZvkEzcrPJuEQTLaHz4KZ3/eFpcuCSrj/jwaK8mcjz1txRi7fQgH5UmzfZVaKWvzD0R18H6g+zcZgYKPX50XrLweemmCH5mgjamB7uvOlc+Ff5BOQN3g2R2uJN2pT15poSVGFMR8Fbk0EO0T0aG8slDKYgk2W5js5/MFqyFfqT8WJQ9Q7lBbcHM5Las8tm1rDTb9wv6XzSZnMwQeZT+iCbrc3fByXNgMUNvZkS62qG9uoEb0N8Ysh1PIPx8wabGwje0rcfeEVIzN/rEkrvEc5dCjQw== niekkeijzer@Nieks-MacBook-Air.local


write_files:
  - path: /etc/sudoers.d/40-deploy-users
    content: '%deploy-users ALL=(ALL:ALL) NOPASSWD:ALL'
    owner: 'root:root'
    permissions: '0440'

package_update: true 
package_upgrade: true 

packages: 
  - linux-virtual-hwe-20.04
  - fail2ban
  - ufw
  - apparmor
  - apparmor-profiles 

runcmd:
  - apt install -f -y 
  - printf "[sshd]\nenabled = true\nbanaction = ufw\n" > /etc/fail2ban/jail.local
  - ufw limit ssh/tcp
  - ufw allow in on eth0
  - ufw logging off
  - ufw enable 
  - sed -i -e "/^PermitRootLogin/s/^.*$/PermitRootLogin no/" /etc/ssh/sshd_config
  - sed -i -e "/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/" /etc/ssh/sshd_config
  - sed -i -e "/^X11Forwarding/s/^.*$/X11Forwarding no/" /etc/ssh/sshd_config
  - systemctl enable fail2ban
  - systemctl enable ufw 
  - apt purge -y lxd lxd-client snapd
  - apt clean 
  - apt auto-clean

power_state:
  mode: reboot 
  timeout: 5
  condition: true
